### ISSUE TITLE
tufup with PyQT6?

### ISSUE THREAD

**Issue by abenzick** [dennisvang/tufup#30] opened 2022-08-21 14:32 UTC
Is the update process with tufup compatible with an exe app created in PyQT6?

**Comment by dennisvang** [comment] 2022-08-22 06:57
@abenzick By design, `tufup` should be compatible with any type of "application bundle." An application bundle, in this context, is just a directory with any type of content, such as your PyQt6-based executable and its dependencies.

Currently we are "beta-testing" `tufup` with some of our own applications based on PyQt5, which are bundled with PyInstaller. We haven't run into any issues yet.

The basic setup for such an application is illustrated in the [tufup-example][1] repository.

If you need any help setting up, please let me know. :)

[1]: https://github.com/dennisvang/tufup-example

**Comment by abenzick** [comment] 2022-08-23 01:58
Could you help me walk through this logic and make sure I understand the world of auto-updating properly?

My application is a compiled .exe made from PyInstaller on a PyQT based GUI app in Python. I currently distribute my app as a downloadable EXE. When I release a new version, people have to download a new EXE and replace the old version.

My understanding with Pyinstaller .exe's is that when they are run, they temporarily expand their contents in temp folders that are destroyed when the app is done. 

How does the TUF based updating work in that? When a new update is applied, is it rewriting and replacing the original EXE with a patched version? Or is it patching the expanded files every time it is run?

I'm doing pretty good with the sample code. I've finished the repo side of things and have the client in my test env detecting a new version. 

I'm testing my Pyinstaller .exe with tufup client code and it can't seem to find the root.json file. I think it has to do with it being in the sys._MEIPASS folder but none of the example code seems to account for that.

**Comment by dennisvang** [comment] 2022-08-23 07:23
> Could you help me walk through this logic and make sure I understand the world of auto-updating properly?

Of course, @abenzick, no problem:

> My application is a compiled .exe made from PyInstaller on a PyQT based GUI app in Python. I currently distribute my app as a downloadable EXE. When I release a new version, people have to download a new EXE and replace the old version.
>
> My understanding with Pyinstaller .exe's is that when they are run, they temporarily expand their contents in temp folders that are destroyed when the app is done.
> 
> How does the TUF based updating work in that? When a new update is applied, is it rewriting and replacing the original EXE with a patched version? Or is it patching the expanded files every time it is run?

`tufup` does not know about the internal workings of PyInstaller, so it does not touch any temporary files created by PyInstaller. All `tufup` does is download the archive containing your new executable, and copy its contents to your app install dir, overwriting the old content. On Windows, the app install dir would typically be a subdirectory of `%PROGRAMFILES%` or `%LOCALAPPDATA%` , but you can specify your own location.

> I'm doing pretty good with the sample code. I've finished the repo side of things and have the client in my test env detecting a new version.
> 
> I'm testing my Pyinstaller .exe with tufup client code and it can't seem to find the root.json file. I think it has to do with it being in the sys._MEIPASS folder but none of the example code seems to account for that.

To enable secure updates, your initial distribution needs to include the `root.json` file. This is necessary, because, before downloading anything, `tufup` (actually `python-tuf`) needs to know which keys can be trusted. By "initial distribution" I mean the executable your users download and install manually.

To include `root.json` in your executable, PyInstaller needs to know where to find it. The location of `root.json` can be specified in your PyInstaller `.spec` file. See, for example, the [tufup-example spec file][1].

I hope this helps. If not, please let me know.

[1]: https://github.com/dennisvang/tufup-example/blob/ce49f3dee1daa86b19915c2b6d58620a1f199951/main.spec#L11

**Comment by abenzick** [comment] 2022-08-25 20:21
Good news! I was able to have my app auto-update! Following your sample, I pushed out a couple of builds and a patch and it detected the patch, applied it and restarted. Wahoo!

Now today I'm facing a "failed to verify timestamp" and it won't check again. I should be able to track that down. I'm seeing some potential as this comes together!

**Comment by dennisvang** [comment] 2022-08-26 07:08
> Good news! I was able to have my app auto-update! Following your sample, I pushed out a couple of builds and a patch and it detected the patch, applied it and restarted. Wahoo!

@abenzick That is good news indeed! I'm happy to hear you got it working. :)

> Now today I'm facing a "failed to verify timestamp" and it won't check again. I should be able to track that down. I'm seeing some potential as this comes together!

This sounds like the timestamp has expired: The TUF metadata files have expiration dates. In the tufup-example, the timestamp file expires after one day, by [default][1]. This means you need to re-sign the timestamp file every day (on the repository side). This would typically be done automatically, on the server. This is explained in more detail in the [TUF docs][2].

To re-sign the timestamp metadata file using the CLI:

```
tufup sign timestamp <path to directory containing private keys for timestamp>
```

You could also use the `-e` option to change the number of days after which the file should expire. 

See `tufup sign --help` for more information.

[1]: https://github.com/dennisvang/tufup-example/blob/ce49f3dee1daa86b19915c2b6d58620a1f199951/repo_settings.py#L38
[2]: https://theupdateframework.io/metadata/#timestamp-metadata-timestampjson

**Comment by dennisvang** [comment] 2022-08-29 06:48
Closing the issue, as I assume this has been answered. If not, please let me know.

**Closed by dennisvang** 2022-08-29 06:48 UTC
Labels: question
